# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8de89d32b3118eab89253460322d7e2"
application_url = "https://mix-partnership-britannica-horses.trycloudflare.com"
embedded = true
name = "enquiry-imporved-3"
handle = "enquiry-imporved-3"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://mix-partnership-britannica-horses.trycloudflare.com/auth/callback",
  "https://mix-partnership-britannica-horses.trycloudflare.com/auth/shopify/callback",
  "https://mix-partnership-britannica-horses.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
