# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b2ba348dea728c9d9969f35860db912"
application_url = "https://spirit-disagree-modelling-parts.trycloudflare.com"
embedded = true
name = "enquiry-app-buildup"
handle = "enquiry-app-buildup"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://spirit-disagree-modelling-parts.trycloudflare.com/auth/callback",
  "https://spirit-disagree-modelling-parts.trycloudflare.com/auth/shopify/callback",
  "https://spirit-disagree-modelling-parts.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
