# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f7295b2910b626d328d3beb471938b0b"
application_url = "https://november-oral-element-cakes.trycloudflare.com"
embedded = true
name = "enquiry-improve-2"
handle = "enquiry-improve-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://november-oral-element-cakes.trycloudflare.com/auth/callback",
  "https://november-oral-element-cakes.trycloudflare.com/auth/shopify/callback",
  "https://november-oral-element-cakes.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
